### ISSUE TITLE
Bar-cursor padding causing confusion

### ISSUE THREAD

**Issue by 1seco** [Sinono3/obsidian-helix#10]
The Bar-cursor padding to the text on the left confuses me between if it is a space I have added or if it is just the bar-cursor padding. It makes it confusing to see when one has to add a space, e.g. for starting a new word/sentence.

Below are two comparisons with the block-cursor with appropriate padding and the bar-cursor issue:

https://github.com/user-attachments/assets/00837b6d-358a-480d-97ff-826679306cca

https://github.com/user-attachments/assets/cd4321e6-9f44-4629-ac76-8ae8ad833489

See if you can adjust the left padding to make the writing experience just a bit better.

Thanks a lot

**Comment by Sinono3** [comment]
Hi. I suspect the bar padding is due to your theme. The issue does not occur on my vault. Can you share the name of the theme you're using?

**Comment by 1seco** [comment]
Ah it's fine. Just to note, this padding issue can get quite a bit worse in monospaced fonts most usually found within backticks. I'll check a bit more how it varies across different formating options.

**Comment by Sinono3** [comment]
Fixed in 0.1.7.
