### ISSUE TITLE
Cursor shape doesn't change

### ISSUE THREAD

**Issue by pivoshenko** [Sinono3/obsidian-helix#7]
@Sinono3

Hi! First of all thanks for your plugin, it's amazing! 
I noticed that the cursor shape doesn't change between NORMAL and INSERT modes. I expected the NOR mode cursor to be "block" and the INS to be "line"
Is there some kind of workaround I can do or maybe it can configured in some config?

Thanks in advance!

I am using MacOS, Obsidian v1.6.5, plugin installed manually

**Comment by Sinono3** [comment]
Hi! This is an upstream issue. Obsidian uses a library called CodeMirror to implement the editor view. All my plugin does is  enable [a Helix keybindings extension someone else made for CodeMirror](https://gitlab.com/_rvidal/codemirror-helix). I think what you suggest should not be difficult to implement. I'll give it a try and put up a PR if I get it working.

**Comment by Sinono3** [comment]
[I've created a merge request in codemirror-helix.](https://gitlab.com/_rvidal/codemirror-helix/-/merge_requests/1)

**Comment by Sinono3** [comment]
The MR was just merged! ([7d81211d](https://gitlab.com/_rvidal/codemirror-helix/-/commit/7d81211db3580a41389a902bb705cc2e7b87f990), [702d9825](https://gitlab.com/_rvidal/codemirror-helix/-/commit/702d9825f9c9641402319b21f7c203abb44c2d33)) Now we need to wait for version 0.0.9 containing this change to be released.

**Comment by Sinono3** [comment]
Implemented in [0.1.6](https://github.com/Sinono3/obsidian-helix/releases/tag/0.1.6).
